# Generated by Django 5.2.1 on 2025-06-10 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_jenis_barang_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='jenis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.jenis'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
