# Generated by Django 5.2.1 on 2025-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_barang_jenis_id_alter_barang_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
