# Generated by Django 5.2.1 on 2025-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_alter_jenis_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField()),
                ('isi', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
